version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
